### ISSUE TITLE
pip freeze

### ISSUE THREAD

**Issue by marjev** [lakyfarky/CoinGecko-Spider#2]
Izvucite popis paketa korištenjem pip-a iz konzole i spremite ga u `requirements.txt` datoteku, kako bi devovi mogli pokrenuti instalaciju svih potrebnih paketa s `pip install -r requirements.txt`.
Taj file može stajati u glavnom direktoriju projekta, gdje su .gitignore i README.

**Comment by lakyfarky** [comment]
done
