### ISSUE TITLE
Renaming files and folders

### ISSUE THREAD

**Issue by marjev** [lakyfarky/CoinGecko-Spider#3]
Bilo bi dobro samo pratit sljedeću konvenciju:

- [x] neka imena direktorija/datoteka u sebi nemaju space ili bilo koji prazni znak. Koristite `_` umjesto razmaka tako da i sustavi koji zbog razmaka ne bi mogli uc u taj direktorij, mogu.
- [x] koristite samo mala slova (brojeve i druge znakove po potrebi, ali pokusajte izbjegavat)

**Comment by lakyfarky** [comment]
done.
