### ISSUE TITLE
Remove commented lines

### ISSUE THREAD

**Issue by marjev** [lakyfarky/CoinGecko-Spider#4]
Možete ovakve linije koda, kada su zakomentirane, maknuti.

Ako vam, pak, u nekom slučaju ovo treba, možemo raspravit pa vidjeti kako bi se dalo to izvesti kroz konfiguracijsku datoteku.

Generalno kod u komentarima nije lijepo za vidjet i nije reprezentabilan, osim ako ne služi kao primjer nečega.

https://github.com/lakyfarky/CoinGecko-Spider/blob/4e07d03c289269a177b12e5e8973fc7b70169d89/Scrapy/spider_CoinGecko/scrapy.cfg#L10

**Comment by lakyfarky** [comment]
done.
