### ISSUE TITLE
Py Cache

### ISSUE THREAD

**Issue by marjev** [lakyfarky/CoinGecko-Spider#5]
Potkralo vam se ovo:
https://github.com/lakyfarky/CoinGecko-Spider/tree/main/Scrapy/spider_CoinGecko/spider_CoinGecko/spiders/__pycache__

mislim da se dogodilo slijedeće:

- išli ste raditi spidera, izgenerirao se pycache, vi ste ga commitali u git
- zatim ste naknadno dodali .gitignore

Već commitano gitignore neće dirati.

Mislim da ćete morati:

- [x] izbrisati pycache i commitati te izmjene
- [x] pokrenuti pauka tako da vam se izgenerira novi pycache
- [x] uvjerit se da vam taj novi generirani pycache git neće uhvatiti kao izmjenu tj. da će `.gitignore` obaviti svoje.

**Comment by lakyfarky** [comment]
.gitignore nakon novog commita nije maknuo pycache

**Comment by lakyfarky** [comment]
done.
